### ISSUE TITLE
Add Hover Effect in “visit us to know more”

### ISSUE THREAD

**Issue by Sandeshjadhav22** [Google-DSC-DMCE/College-Website-HacktoberFest-2023#1]
“Visit Us to know more” Add Hover effect on this button and BG color should be match the website

**Comment by ashfaque-mustaque** [comment]
assign me i will fix this issue.
@Sandeshjadhav22

**Comment by ashfaque-mustaque** [comment]
bro i fixed the issue and now you have unassigned me.
first look my contribution then you can assign or unassign on the basis of my work @Sandeshjadhav22

**Comment by Sandeshjadhav22** [comment]
@ashfaque-mustaque bro initially i assigned it to you but idk how it got unassigned. Also i have merged your PR. Good Work 👏

**Comment by ashfaque-mustaque** [comment]
Thanks Brother
