### ISSUE TITLE
Fix About Slider Function

### ISSUE THREAD

**Issue by Sandeshjadhav22** [Google-DSC-DMCE/College-Website-HacktoberFest-2023#2]
The About Slider in mobile view is not functioning correctly and needs to be fixed

**Comment by Rajiiee** [comment]
@Sandeshjadhav22 assign me the issue and give the details to be fixed

**Comment by Sandeshjadhav22** [comment]
@Rajiiee Sure Go ahead, Fix Slider bar which appers in Mobile View.
![image](https://github.com/Google-DSC-DMCE/College-Website-HacktoberFest-2023/assets/112971248/1dcdae68-18a1-41e7-bb67-0e6491c1f1e3)
